// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllTasks():Promise<Array<main.GetTasks>>;

export function PostTask(arg1:main.Task):Promise<void>;

export function UpdateTask(arg1:number,arg2:main.Task):Promise<void>;
